services:
  mysql:
    image: mysql:latest
    container_name: go-template-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=blog
  
  redis:
    image: redis:latest
    container_name: go-template-redis
    ports:
      - "6379:6379"